export const GET_WEATHER_INFO_REQUEST = "GET_WEATHER_INFO_REQUEST";
export const GET_WEATHER_INFO = "GET_WEATHER_INFO";
export const GET_WEATHER_INFO_FAIL = "GET_WEATHER_INFO_FAIL";

export const GET_TEMP_IN_FAHRENHEIT = "GET_TEMP_IN_FAHRENHEIT";
export const GET_TEMP_IN_FAHRENHEIT_FAIL = "GET_TEMP_IN_FAHRENHEIT_FAIL";

export const GET_TEMP_IN_CELSIUS = "GET_TEMP_IN_CELSIUS";
export const GET_TEMP_IN_CELSIUS_FAIL = "GET_TEMP_IN_CELSIUS_FAIL";
